dockergen-confd: docker-gen -watch -notify "nginx -s reload" /app/nginx.tmpl /etc/nginx/conf.d/default.conf
dockergen-stream: docker-gen -watch -notify "nginx -s reload" /app/nginx.stream.tmpl /etc/nginx/stream.d/default.conf
nginx: nginx
